### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Huluti**

### CODE REVIEW

**Comment by ferdnyc** [comment]
@Huluti Ack! Yeah, that'll cause issues.

I was trying to figure out why it didn't bite me and I could still see Keyboard in the GSConnect menu, but then I realized that because of the discussion in #697 I still have a custom `menu-actions` defined!

Once I removed that, sure enough Keyboard was missing for me as well. Good catch, thanks! Squashing and merging.

**Comment by ferdnyc** [comment]
(#697 also presents a workaround for anyone looking to fix this themselves so they don't have to wait fo the next version to be released. Because you'd have to not only edit the schema file but compile a new schema, to correct this value in the code, it's probably easier to just fix it in dconf:
```sh
# Get the identity of the device (or devices) paired to your computer:
$ dconf read /org/gnome/shell/extensions/gsconnect/devices
['1234567890abcdef', '9876543210fedcba']
# (You'll *probably* only have one, if so you can skip the loop
$ for d in (list bare device IDs here with spaces separating); do \
    dconf write /org/gnome/shell/extensions/gsconnect/device/${d}/menu-actions \
    '["sms", "ring", "mount", "commands", "share", "keyboard"]'; \
   done
# Then trigger a restart of the GSConnect daemon...
$ touch $HOME/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js
```

**Comment by ferdnyc** [comment]
@andyholmes Looks like we're gonna need at least a `v29-rc3`...

**Comment by ferdnyc** [comment]
@andyholmes Oops, never mind, I was behind on my notifications. Make that a bugfix `v30`, I guess.

**Comment by andyholmes** [comment]
Did this actually throw an error or cause problems, or did it just not work?

**Comment by ferdnyc** [comment]
It just didn't work, Keyboard doesn't appear in the menu. No harm other than missing functionality.

**Comment by andyholmes** [comment]
Hmm, I guess I could release v30, but if anyone asks all these mistakes I keep making in odd-numbered releases are actually a homage to Star Trek movies :wink:

I'll give it until the morning to see if any other last minute bugs show up.

**Comment by ferdnyc** [comment]
I'd offer to run point on `v31`, but I'm worried that would be the equivalent of letting Shatner direct.

**Pull request merged**
