### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by andyholmes**
Enjoy!

### CODE REVIEW

**Comment by andyholmes** [comment]
So I'm thinking crowdin is just going to continue to assume *it* has the most up to date version of the german translation, so I'll probably have to copy these over by hand before it can merged.

**Comment by andyholmes** [comment]
@BjoernDaase 

There's a note about the rules of ellipses (`...`) in German on Crowdin, and the other changes seem to be finer points of grammar and vocabulary. My German is at best inherited, so I can muddle through but I can't make a decision about what to copy over.

Would you be okay making these changes on [Crowdin](https://crowdin.com/project/gsconnect/de) instead where you can discuss with other translators? You can login with your Github account, so it's pretty straightforward.

**Comment by andyholmes** [comment]
I'm going to merge this so we can do a release, so unfortunately your current changes will be overwritten for now.

**Comment by BjoernDaase** [comment]
I am sorry Andy, I am super busy right now. It makes absolute sense to overwrite them (for now) to make a release and don't let this block anything :+1: 

I hope I will find some time on the weekend to make my changes in Crowdin if that's ok :)

**Comment by andyholmes** [comment]
Okay, no worries, take your time :)

**Comment by BjoernDaase** [comment]
I added the, form my POV, save bets.  

> There's a note about the rules of ellipses (...) in German on Crowdin

i did not find this so I left them out for now.

**Pull request merged**
