### PR TITLE
Fix Dutch language code

### PR DESCRIPTION
**Pull request by piotrdrag**

### CODE REVIEW

**Comment by Vistaus** [comment]
No, it should be nl_NL to differentiate it from nl_BE (Flemish Dutch is different at some points than Dutch from the Netherlands).

**Comment by piotrdrag** [comment]
Are you going to provide nl_BE translations? Do you know of any project that includes nl_BE? GNOME doesn’t.

**Comment by Vistaus** [comment]
I could name plenty of projects that use nl_BE. I could provide an nl_BE translation of gnome-shell-extension-gsconnect as I also have experience with the Flemish language. That's actually a good idea, 'cause else someone from Belgium could modify the general nl translation to adapt it for Belgian speakers, but then Dutch people will have a hard time understanding.

**Comment by Vistaus** [comment]
@piotrdrag I've added a Flemish (nl_BE) translation now: https://github.com/andyholmes/gnome-shell-extension-gsconnect/pull/187

**Pull request closed without merging**
