### PR TITLE
WIP: Settings ui hints

### LINKED ISSUE #361: Settings UI hints
I'd like to suggest a few changes to the settings window so that it will look like more 'gnomish':
pic1
pic2

The main differences are:
- remove the "refresh" text button from the bottom of the list on the left and put an icon-only button on the headerbar on top (gnome-software does that).
- add a vertical-line/separator on the headerbar (gnome-control-center does that).
- correct the alignment of the text shown in the right half of the headebar.
- replace the 3-dots button with the 3-lines button

Let me know if you appreciate these hints. ;)

### PR DESCRIPTION
**Pull request by andyholmes**
This is a work-in-progress branch to update the settings window to be more like core GNOME applications. The two most prominent change will be to move the *"Refresh"* button into the headerbar and to improve the title alignment.

resolves #361

### CODE REVIEW

**Comment by andyholmes** [comment]
> In fact, although the other commands work fine, I got this error:

Ah, I forgot one command: `git fetch`. But that's okay, it works and we can "rebase" later if we need to.

> Please take a look at what I'm doing. I'm somewhat stuck

Okay, I found a few tough to spot problems, so I decided we should make this a PR to keep working on it. You need to change the permissions to allow me to push the changes before we can continue though. After that I can push changes, then you can pull them, make changes, push them...

So here's a screenshot of where I got it, I think this is more what you were aiming for:

screenshot from 2018-11-29 16-46-46

In this case, one of the old GtkSeparators had 6px margin on the left, that's where the weird invisible space was from. In the *"Common"* tab is properties that all widgets have. This section below you will use a lot when making a UI.

screenshot from 2018-11-29 14-16-55

Simply put, "Expand" means "make this box bigger". "Alignment" has a few options, but "Fill" is confusing because it sounds like "Expand". "Fill" means "Fill but *do not* make it bigger".

> Well... You know, I didn't go deep into this, but I'd prefer to make it work exactly as gnome-control-center.
> Try this: open Settings -> select any item on the list, say 'Bluetooth' -> the Bluetooth page will appear on the right AND the title 'Bluetooth' will be shown on the headerbar on the right.

I think I didn't understand what you meant by this, but now I get it :stuck_out_tongue:. I started to make that change too, but then I realized our settings window is different.

In GNOME Control Center, the page like "Wi-Fi" is a good example. The "secondary menu" by the close button is actually a menu *for* Wi-Fi, but for us it's always the device menu.

screenshot from 2018-11-29 17-04-58

So I'm thinking we can still re-align the title and maybe keep the headerbar separator, but if we change the title for each section (eg. Notifications) it might seem like the menu is supposed to be for that section. There is another option though, we could try it like GNOME Contacts:

screenshot from 2018-11-29 17-01-51

I don't know if I like that, because it's a bit cramped and the menu is in a weird place. But what do you think of all this?

**Comment by amivaleo** [comment]
I didn't received any email for this thread. o.o
Well, here I am now.
I hope I successfully added you as a collaborator, so that you should now be able to push into settings-ui-hints branch.

Let me check a few things before replying to the other 'questions'. 🤔

**Comment by amivaleo** [comment]
So:

I think gnome-contacts has a very rough UI. I'd like to suggest something different, but I'm 99% sure I wouldn't be even listened, at all.
Anyway, what makes the things harder is the fact that the app-menu is going to be removed from gnome 3.32.

My idea is that you have the need to merge in a single window both the gsconnect settings AND the mobile settings.
I came up with these ideas:
schermata da 2018-12-01 19-00-22
schermata da 2018-12-01 19-00-28

I think this is a lot of work. But well, no one is putting pressure on this, no deadline, so... :)
What do you think?
I know I'm cheating now: these screens are a 'change request'. ^_^

**Comment by andyholmes** [comment]
You seem to be pretty interested in design and mockups. You should have a look through [GNOME's GitLab repository for design](https://gitlab.gnome.org/Teams/Design), because I think they have tools and templates that are probably easier to use than Gimp. It seems like the designers there use SVG and have some tool to do their mockups you might find cool.

---

I like *some* parts of your mock-up :) These are big changes so they'd need some discussion (and time).

The main settings page I'm not sure about. I hope to make it a lot simpler and make some of those settings automatic or less prominent. Maybe hide them in a menu because I think most of them only get used once. It would be nice not have a whole page for 2-3 settings :)

I like the "Devices Selected" mockup because it reminds me a lot of GNOME's Bluetooth page, and KDE Connect works a lot like that. The hard part would be finding a way to make the device page elegant, since GNOME's Bluetooth does a popup and I don't really those very much :)

The "tabbed headerbar" is something I tried during gnome-shell-extension-mconnect (I think you used that too), but it didn't work out for a couple reasons. It kind of hogged the whole header bar and the "About" page was difficult. [In Gtk there's an automatic dialog](https://developer.gnome.org/gtk3/stable/GtkAboutDialog.html) that handles the license, credits, translations and all that stuff. Before when I wrote a custom page it never really looked quite right and didn't do the licensing or translations properly.

---

About the headerbar centering, one thing I noticed that's pretty annoying is the window buttons. I only use the close button (and it looks like you do too), so it's easier to center, but look at this :disappointed: 

screenshot from 2018-12-01 19-50-24

I don't know if there's a good way to fix that. We can ignore user settings and do the close button *in* Glade, but that might upset people :P

**Comment by amivaleo** [comment]
> You seem to be pretty interested in design and mockups.

I am. I used to draw some mockup a few months ago. I got in touch with devs, Allan Day, Carlos Soriano, etc.
I quit after a few weeks. That was not my place.


> I think they have tools and templates that are probably easier to use than Gimp.

I used Libreoffice Impress for those pictures I put in my previous message. :)
I think they use inkscape. That's what I was told. Only that. If they have templates, I haven't found them yet.
I'm more about learning how to use glade anyway. Using that as a tool for mockups would shorten the time and effort needed for switching the UI to them.


> I like the "Devices Selected" mockup because it reminds me a lot of GNOME's Bluetooth page

Well... I copied that! ^_^
I like gnome UI, and I start having tremors when I spot some UI which is not perfectly aligned to that, according to my super personal opinion (just to say: I would like to see the search-icon-button always in the same place, either or the right or in the left of the headerbar. In some UI it's on the left, like in Settings, in others its on the right, where I think it should be, like in Nautilus, Geary, etc).
This is how I ended up here (and in that gnome-design chat room)! :D


> I think you used that too

Yes. And I do still remember those stacks of tabs. I don't really like that solution, indeed. I was trying to a different approach anyway.


> About the headerbar centering
I don't know how geary fixed that. Its headerbar is split in two. The left part is crowded with some (too many, imho) buttons. Still, the title is centered.
I downloaded the repo and tried to check that, but its GUI is made up of several files. I opened the one called main-toolbar.ui, which contains the entire headerbar indeed, but there's no gtk object for that title. o.O


> We can ignore user settings and do the close button in Glade, but that might upset people
NO.
That upsets me too. :|
I'll try to look at how Tweaks deal with that. Its 'Extension' page has a switch in the headerbar, but still its title is centered.


Anyway, I suggest to go back to where we were: let's go step-by-step.
My suggestion is to move the 'restart-button' to the left of the 'Service' Label now.


Two questions:
- why do I have this box in this page?
schermata da 2018-12-02 11-06-05
- do you know how to change the background color of gtkbuttons? Some have a blue background, others red. I can't see any option for that in glade. I think I should write the correct words in that "Style Class" field, but I don't understand where to find the complete list of 'allowed words'
schermata da 2018-12-02 11-08-48

**Comment by amivaleo** [comment]
Take a look at the master branch of my fork.
I chenged the UI of the debug.ui a bit.

**Comment by andyholmes** [comment]
> why do I have this box in this page?

That's because the Settings UI has changed too much to be merged automatically. That can be fixed later or you can do a fetch & rebase then resolve the conflicts using something like [Meld](http://meldmerge.org/).

    $ git fetch upstream
    $ git rebase upstream/master

You can always try it and if it's causing problems, you can cancel it like this:

    $ git rebase --abort

> do you know how to change the background color of gtkbuttons?

GtkButtons have two special style classes: `suggested-action` and `destructive-action`. These should only be used rarely though. There some information in the HIG about [Buttons](https://developer.gnome.org/hig/stable/buttons.html). They say that _"Each view should only include a single suggested or destructive button"_.

> Take a look at the master branch of my fork. I changed the UI of the debug.ui a bit.

Unfortunately my laptop died so I will be unable to test or work on GSConnect for at least a week or more :disappointed:.

Probably you should leave the debugger alone though, I change it all the time and it's usually broken. It's really only useful for developing so I will probably remove it by next release and add a "Generate Support Log" like GNOME Builder for users.

**Comment by amivaleo** [comment]
Something wrong here. 🤔
```
$ git fetch upstream
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ git rebase upstream/master
fatal: Needed a single revision
invalid upstream 'upstream/master'
```
I really hate git. 😩

I have to re-read the HIGs. A few things have changed and some I forgot.


> Unfortunately my laptop died

How is it possible? You are supposed to be a geek. You're pc can't die! 😛


> Probably you should leave the debugger alone though

No problem. I was actually playing a bit. :)
For me this is also an opportunity to learn how to use glade.

I'd like to understand how to 'link' GUI and code. I've tried doing that by myself during this weekend but it looks like there's not much in glade about that. 🤔

**Comment by andyholmes** [comment]
Sorry it's been awhile since I commented here. It's hard to keep track just using my phone/tablet :P 

I think my new laptop might be here by Monday though, and I have lots of changes planned (some based on your mockups :D). I think all the dependency stuff will just be removed since it's causing way too many problems and only seems to work on Ubuntu, and only sometimes then.

I think the new main window will be very simple and probably look a lot like Bluetooth in GNOME Control Center. That's probably a good idea anyways if Ubuntu decides to include GSConnect and put a settings page in Control Center like dash-to-dock.

I'll keep you up to date :)

**Comment by amivaleo** [comment]
I remember that, ages ago, when gnome control center main window was a list of icons, you could add icons there.
Can you still do that in a similar quick way?

That would be a nice 'solution'. :)
Your extension is really quite good. I hope such integration will happen.
Also because the control center should be a real control center (no tweaks... :3 ). I approve that! :D Not that anybody cares, but still I like it.
👍

**Comment by ferdnyc** [comment]
A little necromancy here, but today is catch-up day for me...

@andyholmes :
> About the headerbar centering, one thing I noticed that's pretty annoying is the window buttons. I only use the close button (and it looks like you do too), so it's easier to center, but look at this 
> 
> screenshot from 2018-12-01 19-50-24
> 
> I don't know if there's a good way to fix that. We can ignore user settings and do the close button _in_ Glade, but that might upset people :P

It would upset _me_, that's for sure! I turned on those controls because I use them! Heck, you should hear me rage every time I try to double-click a headerbar and the window _doesn't_ windowshade like my titlebar settings say it's supposed to. (And I rage even louder when I do that to Chrome, and it _maximizes_ instead of just ignoring my double-click.)

Honestly, the centering-in-available-space thing never bothered me. It only looks weird when you look at the two options side-by-side — in isolation, the bottom window looks fine: The title is centered in the window titlebar, which the window-management icons aren't really part of (in my mind).

I was going to suggest taking a page from Nautilus and just left-justifying the string after a spacer (and someone record this date, because this is the first time and probably the _last_ time I will ever recommend anything about Nautilus as something to **emulate**), but in the course of preparing to take a screenshot of that I just discovered that Nautilus' headerbar dynamically reconfigures itself to the window width, and the breadcrumb trail actually **_is_ centered** once the window is wide enough. I'm almost impressed, almost.

D-Feet also has a headerbar with two buttons in it that are centered in the width of the window, regardless what else is going on button-wise. So, there's gotta be a way.

(And, in fact, now that you made me notice it, the D-Feet window looks weird to me, because the buttons aren't centered in what I consider "the title bar". **#CannotUnsee**)

screenshot from 2018-12-09 13-12-54

**Comment by amivaleo** [comment]
"coherent design language"
Which is something I like but...
I have just started to use glade and my impression is that too much freedom is given when it comes to send paddings&margins (while you should only be allowed to use multiple of 6, like the HIGs suggest), and there's some lack of "standardisation". 🤔
Just to give an example: the CSS for the GTKmenubars could be tweaked so that they could better intergrate into the design language. Adwaita needs to be "fixed" here.
Some common "recipes" could be shared and imposed to devs. For example: try to notice where the search button is placed in the headerbar. Sometimes it's on the right (gnome-c-c), other times it's on the left (nautilus). The same holds for the save button.
I can produce some of these "non-standardisation proofs", although that would be just a waste of time, because no one would care. Still, the messy GUI is what leads me to bother Andy and other people. 😄
If gnome was some commercial product and had some structured company behind, it would be well beyond these "issues". Thankfully, it's a open source thing yet, although this leads to such a slow development in some areas. 🙁

If gtk widgets had better constraints, and apps had a more "open" (simple) structure, I think that there would be much more contributors and contributes. 🤔

**Comment by ferdnyc** [comment]
> "coherent design language"
> Which is something I like but...

It's one of those things that sounds nice _in **theory**_, but is really hard to do in practice. If you're an 800# gorilla like Apple, you can impose strict design standards and pressure developers to follow them because they need you as much as you need them. And now with their various App Stores, it's even easier, because they can literally _enforce_ the standards by rejecting any app that fails to follow them.

But also if you're Apple, you have the resources to _support_ developers in adhering to those standards — you write coding tools with a knowledge of those standards baked in; you provide good, comprehensive documentation on both the standards and the tools that apply them; and you ensure that the standards are **robust** enough that, while they may _constrain_ people developing for your system, they still _enable_ them to write software that does everything they need it to do — or if they can't, with the current tools/standards, then you work with them to further enhance the operating system so that it meets their needs instead of presenting a roadblock.

The GNOME team, as you note, consistently fail to do any of that. Which isn't their fault! They could never _possibly_ devote the time, effort, and resources (===$BIGMONEY) to such an effort. They're not a multi-billion-dollar company. It's all the core developers can manage to even write all of the _system_ code that goes into GNOME. (And indeed it took them at least 4 or 5 Gnome Shell releases before it started to feel _somewhat_ usable and not full of gaping holes.) Documentation, toolsmithing, writing examples and reference implementations and everything else that goes into supporting a development ecosystem... all of that is just not realistic for them to take on.

And that's the problem. Carrying on like you've got this Grand Design™ for the system that everyone needs to follow because then the world will be sunshine and rainbows, when really what you've got are some half-finished sketches on the back of a napkin (with one part smudged so you're not quite sure what it's supposed to say) just creates an uncomfortable environment for everyone involved.

> For example: try to notice where the search button is placed in the headerbar. Sometimes it's on the right (gnome-c-c), other times it's on the left (nautilus). The same holds for the save button.

Flip that and reverse it, actually, but yeah. However, there **is** actually logic to _that_. Far be it from me to defend the Gnome devs, but... that difference may not be great UI, but it's not arbitrary either. 

The thing with the search button in gnome-c-c, you'll notice, is that search is performed _in the sidebar_. The search box drops down into the sidebar, and the results are displayed in the sidebar. So, having the button directly above the sidebar makes sense, and in fact there's a separator in the header bar between the sidebar part of the window (which contains search), and the rest of the window (which contains the configuration panels). 

In Nautilus, OTOH, search is performed in the area of the header bar that the search button is sitting right next to. (And in fact, as I discovered today, making a Nautilus window wide enough will cause both the breadcrumb trail and the search button to detach from the right side of the header bar and _center_ themselves together at the top of the window.) The search results, OTOH, are displayed in the main pane below. So, in that case, it makes sense to have search occupy the "main" window area, instead of just the sidebar.

It's weird and inconsistent _in its way_, but there is also some convoluted-but-consistent logic to it.

> If gtk widgets had better constraints, and apps had a more "open" (simple) structure, I think that there would be much more contributors and contributes.

I don't know if that's true, but I think we'd all be able to contribute a lot more, and a lot better, code/software.

**Comment by ferdnyc** [comment]
> The thing with the search button in gnome-c-c, you'll notice, is that search is performed _in the sidebar_. The search box drops down into the sidebar, and the results are displayed in the sidebar. So, having the button directly above the sidebar makes sense, and in fact there's a separator in the header bar between the sidebar part of the window (which contains search), and the rest of the window (which contains the configuration panels).

Heh! And in fact, as I just discovered, when you go into Devices > Keyboard or Devices > Printers, which are _searchable_ panels, a search button appears on the **right** side of the main-window area of the headerbar, to search within those panels. But since you're inside Devices, what was the search button for the sidebar has morphed into the Back button to exit the subgroup. I was really hoping I'd find a searchable top-level panel, so there'd be _two_ search buttons in the header bar at the same time, but they were too crafty to get tripped up by a mistake that obvious.

**Comment by andyholmes** [comment]
I just pushed some changes I had half-finished when my laptop died, mostly based on your mockups. It's still a WIP until it will be ready for the next release, but here are some screenshots:

screenshot from 2018-12-09 17-43-00
screenshot from 2018-12-09 17-41-55
screenshot from 2018-12-09 17-42-42

You can't see it in the screenhotshots, but the headerbars center properly now, with the catch being the entry can't be embedded in the headerbar anymore. "Discoverable" is now only turned on automatically, which is how it was meant to be anyways.

The main menu has lost a lot options that shouldn't have been there anyways; restarting the service shouldn't be necessary, the developer's tool is not accessible to users, etc (although those actions can still be run manually). It now looks a lot more like Gnome's Bluetooth settings, which I think is a good thing.

Sorry I ruined your manual merge :stuck_out_tongue_closed_eyes:, but I did incorporate a lot of what was in your mock-ups so I added you as co-author.

**Comment by amivaleo** [comment]
> I just pushed some changes

😱
You already did all the job. :open_mouth: 
Now I've become useless.
But that's... Awesome. ^_^

A few comments:
- I do appreciate the new popover menu for renaming the service/hostname/titlebar. It's closer to what nautilus does.
- Now I see two 'Help' buttons: one on the main window, the other on the hamburger menu. 🤔 Do they open the same link? If so, I wonder if some 'gnome-bigot' ( :D ) would complain about that.
- '"Discoverable" is now only turned on automatically'. Uhm... Why is it meant to be like that? 🤔 Couldn't that work exactly as the Bluetooth page/service works? My pc is 'discoverable' from other bluetooth devices only when the bluetooth page in gnome-control-center is open. I mean: I can already imagine people complaining about that. All in all, is it really needed to keep it on at any time?
- 'a lot options that shouldn't have been there anyways'. I like that. 😊

> I ruined your manual merge

No worries. I am dumb with git.


> I added you as co-author

🥺
Thank you. Although I sincerely believe I don't deserve that: I only bothered you a lot! 😅

**Comment by andyholmes** [comment]
> Now I've become useless.

Not at all, you pushed to me try some things I might not have :+1: 

> I do appreciate the new popover menu for renaming the service/hostname/titlebar. It's closer to what nautilus does.

It's okay for, but I still think it's a bit awkward. Later I might try and find a reliable way to get the local name as a default, eg Asus X999 (like how KDE Connect does on Android).

> Now I see two 'Help' buttons: one on the main window, the other on the hamburger menu.

Yeah, that is weird actually. I guess I worried it might not be seen by super-noobs :P I think later this week I'm going to try and get my sister to test and see if she can figure it out from the start with no help. One place I could put that is in here:

screenshot from 2018-12-10 00-22-08

But maybe the menu "Help" is enough.

> '"Discoverable" is now only turned on automatically'. Uhm... Why is it meant to be like that?

Well, discoverable is sort of a thing I made up. Basically if you're on a network with *a lot* of KDE Connect devices, every device connects to every other device and it can freeze your computer easily. If you restart it happens again as soon as your WiFi connects, so you can get trapped.

Once someone who worked at SUSE reported this bug, because I guess a lot of people have it on their phones *and* work computers (200+ inter-connected broadcasts). I talked with Albert Vaka (lead KDE Connect dev) once about this, but we couldn't come up with an obvious solution. 

So normally your device is always "discoverable". In GSConnect, once 3 unpaired devices connect, we stop accepting new connections or broadcasts ("Discovery Dsiabled") to avoid DDOSing your machine. Unlike Bluetooth, only "turning it on" when the settings is open wouldn't really help, you'd just open the settings and your computer would freeze. Probably I should just relabel it before releasing.

> No worries. I am dumb with git.

Actually I realized I gave your the wrong instructions. I think I gave you the SSH url for Github, and you obviously don't have my private key :stuck_out_tongue_closed_eyes:. That's okay, git takes a little while to get used to, and there's always something you have to look up.

**Comment by amivaleo** [comment]
> Not at all, you pushed to me try some things I might not have 

:)
Thank you.


> It's okay for, but I still think it's a bit awkward.

Well... Yeah indeed. But that is a feature which is nice to have. Let me tell you a 'story':
I used to have two playstation dualshocks bluetooth-paired to my laptop. They were both listed with the same name, so I couldn't figure out which is which. A simple renumbering or renaming feature would have been really helpful...


> Later I might try and find a reliable way to get the local name as a default, eg Asus X999 (like how KDE Connect does on Android).

What about using the 'device-name'? I don't know its name, but it's the one shown in gnome-control-center > Details > About (or Info... Well, the first item in the list) > Device Name.
You could just discard the renaming feature if you use that, because the user could then change such name from the gnome-c-c page (and gsconnect should refresh the name...!).


> it might not be seen by super-noobs

I see. In these cases -> follow the most common trend: put it in the hamburger menu only. 🤔

I dunno, really.


> get my sister to test and see if she can figure it out

😄

> Unlike Bluetooth, only "turning it on" when the settings is open wouldn't really help, you'd just open the settings and your computer would freeze. Probably I should just relabel it before releasing.

🤔🤔🤔
So it will basically work as a smart tv which is always available for screencasting. Even when I'm watching porn and I could push that stream-button by mistake and get my grandma shocked by how novelas evolved lately. 😄


> git takes a little while to get used to

I've been struggling with this sh-t for a while already. I just can't learn that by myself, without a mentor sitting next to me.

**Comment by andyholmes** [comment]
> What about using the 'device-name'?

Ah yeah, that's your hostname. We could use that, that's what KDE Connect and MConnect used to use too.

> I see. In these cases -> follow the most common trend: put it in the hamburger menu only

done :)

> So it will basically work as a smart tv which is always available for screencasting. Even when I'm watching porn and I could push that stream-button by mistake and get my grandma shocked by how novelas evolved lately.

Haha. Yeah sort of, um KDE Connect does a sort of custom broadcast. Basically there's a special IP address `255.255.255.255` where if you send a packet it will go to every computer on your network, even the computer that sent it.

KDE Connect devices send a JSON packet with their IP, port, name, id, plugins, etc to `255.255.255.255`. Then we respond by opening a direct connection to the IP:Port in the JSON packet. If "discoverable" is off, we ignore those and don't dont send them either (except to/from paired devices).

Things like Chromecast etc, use mDNS/multicast (which for Linux is Avahi), but it's pretty similar. Printers also usually use that. There's a WIP for mDNS for KDE Connect, but it might be awhile.

> I just can't learn that by myself, without a mentor sitting next to me.

This is pretty much what I do: https://wiki.gnome.org/GitLab#Using_a_fork_-_Non_GNOME_developer

Best way is to make your own repo and just start using it. For over a year all I did was `git commit` and `git push`, then I started making branches (`git checkout -b my-unstable-feature` and updating it with `master` if it got behind (`git rebase origin/master`). Using something like gitg might help too.

Also Googling `git` + `whatever`. Five minutes ago I had to Google `git revert commit without losing changes` :stuck_out_tongue_closed_eyes:.

**Comment by andyholmes** [comment]
PS. have you seen Sam Hewitt's mockup site? https://mockups.snwh.org/gnome/settings/wifi

**Comment by amivaleo** [comment]
@ferdnyc:

> if you're Apple

Of course if you're not Apple, you don't have any power to impose a specific design. But!
If that is the case (and that IS the case for gnome), you could at least try to give some 'sense of continuity' by making the gtkwidgets more detailed and with some defined constraint.

Let me give some example:

1. There are several ways for creating a 'list'. Consider the places view in nautilus, the index list (or the research results) in evince sidebar, gnome-c-c list/sidebar, gnome-disks list/sidebar, guake preferences sidebar, etc.
If you compare the heights for the items, they're all different! Some by only 1-2px! O_O
You could avoid this if you select a few possible heights. Say: 32px, 48px, 64px. You could do more: you could allow icons only if 48 or 64 are selected. And you could accept only 1-2 different icon sizes from a list...

2. Why are you allowed to use both gtknotebooks and gtklistbox (or gtk-dunno-what-list) to design vertical lists? You could, for example, make gtk notebooks show text rotated by 90 degrees only, if you put tabs along the vertical sides.
If you did that, guake preferences wouldn't use gtknotebooks -> a more coherent design.

3. Gtk containers should only allow a minimum padding of 6px and multiples of 6. If you did that -> Geary wouldn't have weird paddings in the toolbar shown when you're writing an email.

4. If someone is not using gtk3 for its software, tweak Adwaita so that those objects that have an equivalent in gtk3 are drawn similarly.

5. Why gtkmenubar do not follow the HIGs and, thus, can't be properly used with a touchscreen device? (You could tweak Adwaita so that the menubar height is, let's say, 32px, or 48px. Just to say)

Smart constraints will give a much more coherent design among several apps, without removing that much freedom to designers/devs. I actually think some dev could actually feel 'lost' when trying to design the GUI. Look at several extension settings: they're all different, sometime completely messed up:
schermata da 2018-12-10 17-49-25
schermata da 2018-12-10 17-50-13


> However, there is actually logic to that

Sometimes, yes. But is there a reason for which gedit has the new-tab-button on the left, while on epiphany is on the right? 🤔
And! Can you really give such a strong logical explanation but still easy enough to understand for an average user?


> when you go into Devices > Keyboard or Devices > Printers, which are searchable panels, a search button appears on the right side [...]

I hope I explained this misunderstanding yesterday. Still, let me say that with a picture:
senzanome
Who chooses where that thing should go? Well, let's sit together once and let's find its place. And from then on, please use that, fork repos, ask devs to move it, whatever. You're not Apple, ok, but you're not even try to fix very small issues (Have you evere noticed that gnome contacts sidebar has an extra 1px border? Look right below the headerbar, or the right side in the picture:
schermata da 2018-12-10 18-03-22

> I was really hoping I'd find [...] two search buttons in the header bar at the same time

geary has two search-buttons on the headerbar. ^_^


@andyholmes:
> have you seen Sam Hewitt's mockup site?

Nope. 😱
Who's this good designer? D:
I mean: gnome devs have ever cared about his mockups...?

**Comment by amivaleo** [comment]
You don't reply anymore. :(
Did I say something so bad that now you consider me like some idiot...? :(

**Comment by andyholmes** [comment]
Haha, nope. I've just been busy :P 

I know Sam Hewitt did Suru/Yaru icons, I feel like he might do stuff with either elementaryOS or maybe Pop!_OS? I'm not sure, but I see him in #gnome-design a lot.

> you could at least try to give some 'sense of continuity' by making the gtkwidgets more detailed and with some defined constraint.

Around the time Gnome3 came out, maybe a bit before, we used to do this thing 100 papercuts. It was pretty much things like this. There was a list of tiny annoyances and we'd go through all the applications and fix them. I remember one year one was all instances of "file system" and "filesystem" changed to be "filesystem". I don't know why we don't do 100 papercuts anymore, maybe there's just not enough people.

> Have you evere noticed that gnome contacts sidebar has an extra 1px border? 

Looks like that actually [got fixed a few months ago](https://gitlab.gnome.org/GNOME/gnome-contacts/commit/d78e07eaad1d6b370b8542f0002b4817e52fc71a) :P Sometimes the best way to get something changed is just to do it and submit a PR.

[Sometimes they get rejected](https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/merge_requests/61), but you'll usually get a reason why. Sometimes devs want to get to know you before your opinions are really considered, but I bet if you had submitted that as a PR it would have accepted, maybe with some review conditions before it was merged.

> Smart constraints will give a much more coherent design among several apps, without removing that much freedom to designers/devs.

Sometimes that's true, but it's actually pretty hard to pick a default that works for every case. It's also better for performance sometimes to pick one default for all widgets, and change it if you need to. The reason those switches are all stretched is because the default for widgets is `Gtk.Align.FILL` which means, take all space given and center in it. I guess for switches there could be a default width though, but I'm not actually sure what a GtkSwitch is (without looking, lazy :P); I bet it's a GtkButton subclass.

**Comment by amivaleo** [comment]
> Haha, nope. I've just been busy :P

You two guys are nice. Thank you, for your time in particular. :)

> I know Sam Hewitt did Suru/Yaru icons, I feel like he might do stuff with either elementaryOS or maybe Pop!_OS? I'm not sure, but I see him in #gnome-design a lot.

I don't want to join that room again. I know I would get irritated in no time... 🙄
This sounds wrong, I'm sure of that, especially in a open-source area: I get tired of wasting days or weeks for taking every single decision. And after some months, fashion changes, and you have to re-take decisions on the same stuff.
I saw you read my comment on OMG Ubuntu, about the 'never-ending discussion about a standard design'.
This is exactly what I meant.

> I don't know why we don't do 100 papercuts anymore, maybe there's just not enough people.

Devs are not in touch with users anymore? It could be something like that.
I mean: I'm definitely not a dev. I can only write some simple script for my 'scientific task'. I am definitely a user, not a newbie.
Sometimes I tried to get in touch with devs (here I am indeed!), but sometimes it's like being in front of a concrete wall: there's no space even for a discussion (ah-ehm... some GIMP dev... cough cough).
Then I get so fu**ing angry that I unistall their software! o.o
We could simply discuss and if you can explain the logic behind your choices, that's fair. I appreciate csoriano: he does that.

> Sometimes the best way to get something changed is just to do it and submit a PR.

True, true.
I've just started understanding how to use glade. I downloaded gnome-contacts master branch and I couldn't understand how to fix that. 🤷‍♂️
But I mean... This is something which is really puzzling to me: how happen that *I* can spot such superficial and evident gui errors? I mean: how many people out there use gnome?! o.o Don't you guys use your own software? It's not about using a different gtkwidget or a different layout (like you did with gsconnet settings gui), some just can't see that 1 extra px or the abnormal wide gtkswitches?
If something looks unreasonably ugly, I tend not to use it. 🤔 (why is my mind thinking about girlfriends!? Gosh... I'm insane).

> Sometimes devs want to get to know you before your opinions are really considered

Sure! I definitely understand that. And since this holds for you too, guys, well... This is me: https://www.deviantart.com/amivaleo
Old mockups made using gimp. Some are simply 'bad'. ^_^
Anyway: I usually only try to give ideas. You may or may not like them, that's totally ok. I mean: you guys could have told me "sorry, we prefer to keep gsconnect like it is now, BECAUSE...". As long as you can give a 'good' and logical explanation... 🤷‍♂️
Some can't.
Everything I ask is usually public. If you reply to me, the next noisy guy like me who wants to suggest similar ideas, could happen to read that reply. So: give your explanation once and no one is going to ask the same thing again (maybe...).
Csoriano did that: he said the goal is to get desktop icons and nautilus icons to look as similar as possible. -> no one is going to ask again about adding tiny desktop icon sizes.

> Sometimes that's true, but it's actually pretty hard to pick a default that works for every case.

Well, you don't have to put constraints everywhere, only for the sake of putting constraints.
They could be just a few basic things. Say: all headerbars must have the same height -> force the gtkheaderbar to completely ignore the heights of any contained widgets. It could be things like these.

> without looking, lazy :P
I'm the gtk newbie here. If you're lazy, how should I define myself? ^_^

**Comment by andyholmes** [comment]
I'm going to close this one up for now, because I think most of the proposed changes made it into v19. Feel free to open a new one if you have more ideas :)

**Pull request closed without merging**
