### PR TITLE
Mousepad plugin - generate unicode with composition

### PR DESCRIPTION
**Pull request by getzze**
In Gnome, unicode character can be output by pressing Control+Shift+u, then hexadecimal code, then Enter (https://help.gnome.org/users/gnome-help/stable/tips-specialchars.html.en). This mimics this composition, both using At-spi and Caribou.

It has Left Control and Left Shift keycodes hardcoded. It should be fine for most users but not if these keys are used for another purpose (composing key for example).

It requires testing and should probably be optional and activable in the plugin settings.

Modifiers can be implemented like this too, so we can eventually get rid of Caribou (#340).

### CODE REVIEW

**Comment by andyholmes** [comment]
Cool, I'll try and give this a test asap, but I think hold of until after v20 before merging. That should be in a just a few days, then I'll have closer look. Seems pretty straight forward though.

**Comment by andyholmes** [comment]
By the way, the development tool is still there, it's just hidden from users since many were causing problems for themselves. You can launch it manually:

    gapplication action org.gnome.Shell.Extensions.GSConnect devel

**Comment by andyholmes** [comment]
I pushed some changes; minor changes I guess was a bad commit title :P 

I added some phony `mode_lock()` functions for doing modifiers with keycodes. I'm not sure I understand this as well as you, but it seemed to work perfect for me. I guess that if this works Caribou is still required for Unicode with modifiers, but I couldn't find a way to do that with Android even with Hacker's Keyboard, so I'm not too worried.

Is there a reasonable way to detect if a keycode is being used as the compose key? I don't use this feature so I'm unfamiliar with it.

**Comment by ferdnyc** [comment]
> Is there a reasonable way to detect if a keycode is being used as the compose key? I don't use this feature so I'm unfamiliar with it.

Probably not, but it also shouldn't be necessary since Compose isn't a modifier. Compose is a normal key that initiates a special input mode. (Handy because you don't have to hold it down while pressing the other keys; _especially_ handy since some of them have to be shifted.) That mode terminates when the Compose sequence is complete, which can involve anywhere from two to four (theoretically more, even) keypresses following the key bound to Compose itself.

I have my <kbd>Menu</kbd> key bound to Compose, so I type...
* <kbd>Menu</kbd><kbd>.</kbd><kbd>=</kbd>: •
* <kbd>Menu</kbd><kbd>-</kbd><kbd>-</kbd><kbd>.</kbd>: –
* <kbd>Menu</kbd><kbd>C</kbd><kbd>C</kbd><kbd>C</kbd><kbd>P</kbd>: ☭ (that one's still my favorite) :grin: 

Point is, whatever key is bound to Compose requires no special input handling.

**Comment by ferdnyc** [comment]
I guess the only thing you _might_ have to detect is the fact that the Compose key is NOT being used as a modifier, even if it normally would be.

Like I said, I use <kbd>Menu</kbd>, which normally _is_ a modifier, I think? `mod3`, looks like, from the output of `xmodmap -pm`. But because I have it set to Compose...

```console
$ # While xmodmap -pk stills shows it as Multi_key:
$ xmodmap -pk |grep 135
    135    	0xff20 (Multi_key)	0xff20 (Multi_key)	0xff20 (Multi_key)	0xff20 (Multi_key)	

$ # It's not listed as bound to any modifier in xmodmap -pm:
$ xmodmap -pm
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

**Comment by andyholmes** [comment]
Ok I see now. Well, I guess really anyone using a compose key will think of that key as a compose key, so maybe it's not a problem at all. The only corner case would be if they used eg Alt_L as their compose key and Alt_R as their "regular Alt", whereas for us Alt === Alt_L.

I just pushed an amendment to read keycodes from Gdk during `_init()` so hopefully that's one less corner case to deal with.

**Comment by andyholmes** [comment]
I'm going to go ahead and merge this for now. I think it'll be awhile before the next release, but maybe we'll do another series of RC's so this and GVFS get some good testing.

**Pull request merged**
